name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies and build React app
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Step 4: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      # Step 6: Save Docker image to tar file
      - name: Save Docker image to file
        run: |
          docker save -o react-app.tar ${{ secrets.DOCKER_IMAGE_NAME }}

      # Step 7: Transfer Docker image to EC2
      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./react-app.tar"
          target: "~/react-app.tar"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 8: SSH into EC2 and load Docker image
      - name: SSH and Load Docker image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker
            sudo docker load -i ~/react-app.tar

            # Stop and remove existing container if any
            sudo docker stop my-react-app-container || true
            sudo docker rm my-react-app-container || true

            # Run the new container
            sudo docker run -d -p 80:80 --name my-react-app-container ${{ secrets.DOCKER_IMAGE_NAME }}
